# Generated by Django 5.2.4 on 2025-08-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this exercise', null=True),
        ),
    ]
