# Generated by Django 5.2.4 on 2025-08-04 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the program', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercise Program',
                'verbose_name_plural': 'Exercise Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_sets', models.PositiveSmallIntegerField(default=3, help_text='Default number of sets')),
                ('default_reps', models.PositiveSmallIntegerField(default=10, help_text='Default number of repetitions')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order in the program')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_exercises', to='exercises.exercise')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_exercises', to='programs.exerciseprogram')),
            ],
            options={
                'verbose_name': 'Program Exercise',
                'verbose_name_plural': 'Program Exercises',
                'ordering': ['order'],
                'unique_together': {('program', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='exerciseprogram',
            name='exercises',
            field=models.ManyToManyField(related_name='programs', through='programs.ProgramExercise', to='exercises.exercise'),
        ),
    ]
