# Generated by Django 5.2.4 on 2025-08-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programexercise',
            name='default_rest_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Default rest time between sets in seconds', null=True),
        ),
    ]
